### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by laurentbartholdi** [linbox-team/linbox#20] opened 2015-11-22 21:00 UTC
Hi,
I tried various options to compile linbox, but all failed. I managed to get fflas and givaro installed, and ran ./autogen.sh --with-fflas-ffpack=/usr/local (using clang compiler)
and also tried
./autogen.sh --with-fflas-ffpack=/usr/local CXX='/usr/local/bin/g++ -std=c++11 -Wa,-q' (the recent 4.8 gnu compiler)
then 'make install' failed in both cases, at the same places. Attached is a log of the compilation. Thanks in advance!
[log.txt](https://github.com/linbox-team/linbox/files/41152/log.txt)

**Comment by ClementPernet** [comment] 2015-11-30 17:29
Hi,

Are you compiling on a 32 bits machine? These ambiguous size_t != uint64_t seem to indicate something like this.
I fixed all issues of this type (according from your log), by casts to uint64_t.
Do you confirm it solves them on your machine. I do not have a 32bit box at hand now to test it.

Now concerning the fplll case, it's likely that you have an old fplll in /usr/local, and we do not check correctly the required version before decalring that LinBox can use it.
Can you tell us which fplll version are you using?

Thanks.

**Comment by laurentbartholdi** [comment] 2015-11-30 17:43
Dear Clément:
Thanks for the quick reply!
I tried to compile on lots of machines:
1) a macbook pro (osx 10.9.5, and both g++ 5.2.0 and clang++ 600.0.57)
2) a linux machine with g++ 4.8.4
3) another linux machine with g++ 4.5.
4) another linux machine with g++ 4.9.2

and only combination 2) worked. All these machines are 64-bit (x86_64). The
fplll version is 4.0.1.

I'll try again on these machines; should I pull new sources from github?

**Comment by ClementPernet** [comment] 2015-11-30 19:45
Very strange.
I tested the test-suite of the 3 libs on a 32bits linux box with gcc-4.8.2 and it worked fine, so this is unrelated to 32bit.
I have no access to a osx for the moment, but will try to find one.
Note that gcc versions below 4.7 are not supported (we should actually enforce it).
I am very surprised by 4), since linux and gcc-4.9.2 is what we are commonly using. What distro is it?
Can you publish  your config.log also?
Yes, please pull the new sources on the three projects: givaro, fflas-ffpack and linbox and recompile them.
Thanks.

**Comment by laurentbartholdi** [comment] 2015-12-01 11:28
Dear Clément:
I just pulled the latest files from github, and now givaro doesn't compile.
Attached is the config.log and compilation log, obtained by
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/sw/tools/gnu/gcc-4.9.2/libexec/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.9.2/configure --with-gmp=/sw/tools/gnu/gmp-6.0.0/
--with-mpfr=/sw/tools/mpfr/mpfr-3.1.2 --with-mpc=/sw/tools/mpc/mpc-1.0.2
--with-ppl=/sw/tools/gnu/ppl-1.1/
--with-cloog=/sw/tools/cloog/cloog-0.18.1/ --enable-languages=all
--prefix=/sw/tools/gnu/gcc-4.9.2/
Thread model: posix
gcc version 4.9.2 (GCC)
$ make install > log 2>&1

Hope this helps! Laurent

**Comment by ClementPernet** [comment] 2015-12-01 14:53
Hi Laurent,

Sorry but there is no attachement to your message (can you post directly on the github thread, and post the file as you did on your first post?).

**Comment by ClementPernet** [comment] 2015-12-08 09:37
Hi Laurent, 
Can you please post you config log? It was not attached in your first message?
Thanks.

**Comment by ClementPernet** [comment] 2016-06-06 08:09
Ok, we now have a jenkins build farm, and could reproduce the compilation failures on OSX due to ambiguous casts between size_t and int64_t. This was due to a change of interface in Givaro.
This is now fixed in fflas-ffpack and linbox.

**Closed by ClementPernet** 2016-06-06 08:09 UTC
