### ISSUE TITLE
solve seems broken for sparse integer systems

### ISSUE THREAD

**Issue by videlec** [linbox-team/linbox#56] opened 2017-05-29 08:19 UTC
I am trying to solve sparse systems over rationals. I am using the fuction `solve` with the methods `BlasElimination`, `SparseElimination` and `Wiedemann` as given in the sample file `examples/solve.C`. As far as I tested the `BlasElimination` works fine. However with both `SparseElimination` and `Wiedemann` the function `solve` does not work with non-square matrices. More precisely, the output vector remains unchanged. Here are three examples the two last being wrong with `sparse` and `wiedemann` arguments. The source file of the program is [solve_cpp_code.txt](https://github.com/linbox-team/linbox/files/1035235/solve_cpp_code.txt).

A square system [A1.txt](https://github.com/linbox-team/linbox/files/1035223/A1.txt) [b1.txt](https://github.com/linbox-team/linbox/files/1035227/b1.txt)

    $ ./solve A1.txt b1.txt blas
    M = [[1, 1 ], [1, 1 ]]
    B = [1 1 ]
    A = [1 0 ]/1
    $ ./solve A1.txt b1.txt sparse
    M = [[1, 1 ], [1, 1 ]]
    B = [1 1 ]
    A = [1 0 ]/1
    $ ./solve A1.txt b1.txt wiedemann
    M = [[1, 1 ], [1, 1 ]]
    B = [1 1 ]
    A = [1 0 ]/1

A simple over determined system [A2.txt](https://github.com/linbox-team/linbox/files/1035224/A2.txt) [b2.txt](https://github.com/linbox-team/linbox/files/1035225/b2.txt)

    $ ./solve A2.txt b2.txt blas
    using blas elimination
    M = [[1, 1 ]]
    B = [1 ]
    A = [1 0 ]/1
    $ ./solve A2.txt b2.txt sparse
    using sparse elimination
    M = [[1, 1 ]]
    B = [1 ]
    A = [0 0 ]/0
    $ ./solve A2.txt b2.txt wiedemann
    using Wiedemann
    M = [[1, 1 ]]
    B = [1 ]
    A = [0 0 ]/0

A simple subdetermined system [A3.txt](https://github.com/linbox-team/linbox/files/1035222/A3.txt) [b3.txt](https://github.com/linbox-team/linbox/files/1035226/b3.txt)

    $ ./solve A3.txt b3.txt blas
    using blas elimination
    M = [[1 ], [1 ]]
    B = [1 1 ]
    A = [1 ]/1
    $ ./solve A3.txt b3.txt sparse
    using sparse elimination
    M = [[1 ], [1 ]]
    B = [1 1 ]
    A = [0 ]/0
    $ ./solve A3.txt b3.txt wiedemann
    using Wiedemann
    M = [[1 ], [1 ]]
    B = [1 1 ]
    A = [0 ]/0

**Comment by jgdumas** [comment] 2017-05-31 11:46
Hello, thanks for the report.
I cannot reproduce with the lastest versions.
So I think this has been corrected. Are you using the stable release ?

**Comment by videlec** [comment] 2017-05-31 13:32
don't know. I am using the version that is in Sage.

**Comment by jgdumas** [comment] 2017-05-31 15:18
Sorry, ok i could reproduce it on the current version.
I am looking at solving it now.

**Comment by videlec** [comment] 2017-05-31 19:49
Thanks! I really needed this for huge overdetermined systems (see [this thread](https://groups.google.com/forum/#!topic/sage-devel/CfWRDIIEKnQ). I then started to interface linbox and got stuck on this bug.

It would be wonderful if that can be fixed and can be made as a patch to be used in Sage before next linbox release.

**Comment by ClementPernet** [comment] 2017-06-07 12:50
Ok we fixed a few problems related to dimensions in the specialization of the Dixon solver for sparse and blackbox matrices. The fix is just one commit : 468dc82845ef424cd9b66ef34129d397759c7680 from which you can easily form a patch for previous version (including 1.4.2 shipped in sage). Let me know if you want me to do it.
Meanwhile, we would like rework the test suite which failed to catch this bug, and will probably clean up some code in the Dixon solver. This will be a new issue.

**Comment by videlec** [comment] 2017-06-07 13:03
Wonderful, I opened [Sage trac ticket #23158](https://trac.sagemath.org/ticket/23158). I won't have time to work on it before quite some time. If you have time, please do it.

**Comment by ClementPernet** [comment] 2017-06-08 08:04
Closing as the issue is fixed for the code sent by @videlec . Feel free to reopen, if the issue remains on another instance.
Follow up on cleaning up the solve solution/algorithm code in issue #61

**Comment by videlec** [comment] 2017-06-11 08:35
(note: I am not allowed to reopen the issue)

The patch fixes the trivial examples I gave. However it fails on many other instances with sparse elimination and Wiedemann such as

- `A = [[1 0]]` and `b = [1]` -> obtain zero vector
- `A = [[-2  0] [ 0  0]]` and `b = [-4 0]` -> obtain zero denominator
- `A = [[0]]` and `b = [0]` -> SEGFAULT

**Comment by ClementPernet** [comment] 2017-06-20 08:15
Hi, just to acknowledge that I've read your second report. I've started to track this bug,  It's a completely different one, in the way we compute the bound for the rational reconstruction: with a non-singular rectangular matrix, a column may be zero, and the Hadamard's column bound will then be zero too. We're discussing how to fix it in a consistent way.

**Comment by videlec** [comment] 2017-08-25 16:39
any news on this?

**Comment by jgdumas** [comment] 2017-10-05 15:33
PR #72 should solve this now.

**Comment by ClementPernet** [comment] 2017-10-06 20:54
PR #72 merged upstream. Closing.

**Closed by ClementPernet** 2017-10-06 20:54 UTC
Labels: DevDay2

**Comment by videlec** [comment] 2017-10-20 07:58
Great

@ClementPernet Could you update the patch at https://trac.sagemath.org/ticket/23158 if it is not too complicated? I failed in trying to get one.

**Comment by ClementPernet** [comment] 2017-10-20 08:02
Indeed, it's on my todo list. Note that we're also planning on releasing all 3 libraries soon (within a few weeks), and I'll create a sage ticket for updating the spkg. So maybe the fix could be done there instead of patching linbox-1.4.2.

**Comment by videlec** [comment] 2017-10-20 08:10
Indeed, a new release would be infinitely better! Please put me in cc when you open the ticket.
