### ISSUE TITLE
LinboxMathInconsistentSystem exception when solving with a rank deficient matrix

### ISSUE THREAD

**Issue by Breush** [linbox-team/linbox#148] opened 2018-11-30 10:30 UTC
- Within Z domain, the matrix A is full rank, so that "Ax = b" has a solution named y
- But taken mod p (8386579 a real prime), we get an LinboxMathInconsistentSystem exception
- This exception shouldn't occur because "y mod p" is at least one solution for "(A mod p) x = (b mod p)"

Failing test:

```C++
#include "linbox/matrix/dense-matrix.h"

using Field = Givaro::ModularBalanced<double>;

std::string AData = R"(13 13
-25745341129  64513345946  36141424919 -43921425307  36928315946   5493433813 -16266862276  30758647212  58717383407   2137020060 -26022096376  64008988798  67805280461
 27827089311  10392694339 -13752997288  46201491488 -23742655731 -33715013870  52237453077 -21462158178  47307082447  11304412311  20360743533  67645607710  22441032327
  4485485469  -7240772726 -45757199494   9967193641  18038826611  40628583942  66115872570   2711723123  67996935430  28048063366 -55435705845 -11386854437  18808152680
 28424806166 -58973353072 -59538137641 -65200145958  48283072709 -41798877704  52648763953  41866085163   9658655543   8198192659  40406109601  19788855725  20806442022
-40743658459  60322400041 -20473079457  34487616970  -7107199286 -59480503982 -38104575395   -280955286  24836446211 -54393326972  68503152990 -57803886074  61022916476
 13106001634   5817673132 -39605010826  48900198731  27571965929 -51076417706 -10909376243 -10460023595  16916203661   9412452066 -12492128005 -11725929270  -8706365908
 12249374581  24186737955  57984287598  45839967914  24949679472 -28428335830  59596548975  31245746534  31257428346 -12700309064 -19118162543  43342556593   1044090890
-30813101106 -41473245452 -52440053266  -9247859967  58883433171 -30397345627  -7762356878  42693118659 -33918006160   -553212227  55228337826 -68252265132  25814647624
-44746620446 -51917063709  -1349858093  21188801480  28520437710   1551193587 -62011433573  26274439224 -22712657592  28996852255 -53660796711  45083003852 -25040983746
-36125776219  42142210768  11530600248 -40208476133 -11105317379  46577461503 -66298915653 -37588257583  18693252654  14496687436  65543451096 -42958763541  34048468379
-25909037820  32034548067  -9339104323 -44166085354  -7798934343  44990933258  54381519843 -54294303703  42716436354  62962123677  54653584513 -68619325609 -50656756059
 13103885291 -27381136378 -47557881768 -30508482178  36576296254 -62930690969 -56365684969  58343201584  49944252497 -45722808907 -19193604138  31318340160  38604020610
  2792268904  21786875593 -38381548584  31489273432  62461607282  66076516691  33223533904  25264480665  52493163712    720284411  -1591625359 -53865841123  -4303429210
 )";

std::string BData = R"(13 1
-25745341129 64513345946 36141424919 -43921425307 36928315946 5493433813-16266862276 30758647212 58717383407 2137020060 -26022096376 64008988798 67805280461
)";

int main(void) {
    Field F(8386579);

    LinBox::BlasMatrix<Field> A(F);
    std::stringstream AStream(AData);
    A.read(AStream);

    LinBox::BlasMatrix<Field> B(F);
    std::stringstream BStream(BData);
    B.read(BStream);

    LinBox::BlasVector<Field> b(F, B.rowdim());
    for (auto i = 0; i < B.rowdim(); ++i) {
        b.setEntry(i, B.getEntry(i, 0));
    }

    LinBox::BlasVector<Field> x(F, b.size());

    LinBox::LQUPMatrix<Field> LQUP(A);
    LQUP.left_solve(x, b);

    return 0;
}
```

**Comment by ClementPernet** [comment] 2018-11-30 16:09
This is actually an inconsistent system mod 8386579.
```
sage: A
[1456401 3780278 3656008 7475495 2208609  224568 3100984 5062019 2943828 6828994 1458261 2617870 8175825]
[ 420189 1722958  992272 8214356 8135997 7420289 5839065 7484062 6776887 7690398 6516300 7848075 6933502]
[7052283 5231530 8362109 3937789 7681761 3995266 4470313 2858106 6939477 3343190 7967924 2119845 5442562]
[2689935 1070456 6573259 5505767 1537406 8218611 6207570  282795 5703114 4504976 7958558 4915864 7726102]
[6728902 6123873 6946461 2004122 4619706 5500865 4039581 4188400 3785792 2024422 1575718 4802973 2167672]
[6165236 5773885 4801791 6443161 5280756 6234983 1563036 6426997  473818 2710428 3874705 6894751 7289673]
[4969241 8230698 7866971 7313679 7993526 2166980 1518601 5739759  648413 5358121 3237577  716321 4155094]
[7576719 6774282 1225221 2536670 1262012 4003248 3615276 5431549 5705895  301987 2715111 6101349  757462]
[4165098 4246880  381126 4302926 6069110 8063051 7318132 7673796 6584919 4448652 4922310 5141727 1341148]
[3606113 8037872 7440702 5170172 6899796 6788316 5377921  389495 7954642 4678924 2336211 5680676 7344218]
[5491290 6202866 3544683 6026239  584127 5323502 2941607  408743 3589507 4075124 6635749 8050348 6567680]
[4048893 1044057 2407741 1892224 2425235 2197847  512490 6158060 2174552  819801 3275193 2854174  597473]
[7924676 6929930 3823499 6055866 6753469 7047329 4294485 4104717 1565751 7425196 1824651 1155794 7272396]
sage: A.parent()
Full MatrixSpace of 13 by 13 dense matrices over Finite Field of size 8386579
sage: b
[1456401]
[3780278]
[3656008]
[7475495]
[2208609]
[ 224568]
[3100984]
[5062019]
[2943828]
[6828994]
[1458261]
[2617870]
[8175825]
sage: b.parent()
Full MatrixSpace of 13 by 1 dense matrices over Finite Field of size 8386579
sage: A.solve_right(b)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-1961382592eb> in <module>()
----> 1 A.solve_right(b)

/usr/local/sage/local/lib/python2.7/site-packages/sage/matrix/matrix2.pyx in sage.matrix.matrix2.Matrix.solve_right (build/cythonized/sage/matrix/matrix2.c:8347)()
    446 
    447         if self.rank() != self.nrows():
--> 448             X = self._solve_right_general(C, check=check)
    449         else:
    450             X = self._solve_right_nonsingular_square(C, check_rank=False)

/usr/local/sage/local/lib/python2.7/site-packages/sage/matrix/matrix2.pyx in sage.matrix.matrix2.Matrix._solve_right_general (build/cythonized/sage/matrix/matrix2.c:9664)()
    562             # Have to check that we actually solved the equation.
    563             if self*X != B:
--> 564                 raise ValueError("matrix equation has no solutions")
    565         return X
    566 

ValueError: matrix equation has no solutions
sage: A.augment(b).rank()
13
sage: A.rank()
12
```

This means that the bug is not in the solver mod p, but in the reduction mod p: somehow A or b is not correctly reduced mod p.
Could you publish the value of A and b over Z ?

**Comment by Breush** [comment] 2018-11-30 16:11
@ClementPernet The provided A and B are not reduced.

**Comment by ClementPernet** [comment] 2018-11-30 16:42
Ok, I just realized that this situation can indeed happen: a consistent system may reduce to an inconsistent one mod p. Think of A=[p] and b=[1].
The solution to bug is to catch these exception at the chinese remaindering level and discard the prime that raised this exception.
Thinking about it, we also need to make sure that the case where the system is consistent but rank deficient is correctly handled: it should also be discarded (as ffpack may output an arbitrary solution among the vector space of solutions, and the CRT lift will fail with it.

**Comment by bdsaunders** [comment] 2018-11-30 16:42
If AX = B has a diophantine solution (integer X), then that solution is
valid mod p even if rank(A) decreases.  But if a rational solution is being
constructed this prime may fail because it divides the denominator of X
(and it should just be discarded when using CRA).

**Comment by ClementPernet** [comment] 2018-11-30 16:48
Yes @bdsaunders , this was the purpose of my last sentence. #149 is the followup issue dealing with this problem. 
I'm therefore closing this one, as it is not a bug.

**Closed by ClementPernet** 2018-11-30 16:48 UTC
