### ISSUE TITLE
test-charpoly and test-cra fail with "Illegal instruction" on i386

### ISSUE THREAD

**Issue by tobihan** [linbox-team/linbox#44] opened 2016-11-09 19:05 UTC
Hi,

as the title says, the tests fail on i386, see https://bugs.debian.org/840458
and the full build log at 
https://buildd.debian.org/status/fetch.php?pkg=linbox&arch=i386&ver=1.4.2-2&stamp=1478543427

By the way, if you have an amd64 Linux machine, you can reproduce this in a i386 chroot environment. (For Debian or Ubuntu see https://wiki.debian.org/Schroot)

**Comment by jgmbenoit** [comment] 2016-11-14 21:52
As a matter of fact, I can reproduce it on an amd64 Debian/Sid schroot machine.
Even better, I could isolate a bit from where it is emitted:
new_act->_timer.start (); in linbox/util/commentator.C

**Comment by ClementPernet** [comment] 2017-11-17 14:43
According to the discussion in the debian bug thread, this seems related to the fact that givaro was compiled with some SIMD instructions set on, and the machine where linbox was compiled did not offer these instructions.
This bug should be fixed since we changed the way we set these instruction set options and allow to selectively disable them..
Closing it.

**Closed by ClementPernet** 2017-11-17 14:43 UTC
